name: Build emscript-sdk using main branches

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout emscript-releng
        uses: actions/checkout@v4
        with:
          repository: em-foundation/emscript-releng
          ref: main
          path: emscript-releng
          token: ${{ secrets.token }}

      - name: Checkout emscript-tools
        uses: actions/checkout@v4
        with:
          repository: em-foundation/emscript-tools
          ref: main
          path: emscript-tools
          token: ${{ secrets.token }}

      - name: Checkout emscript-content
        uses: actions/checkout@v4
        with:
          repository: em-foundation/emscript-content
          ref: main
          path: emscript-content
          token: ${{ secrets.token }}

      - name: Checkout emscript-sdk
        uses: actions/checkout@v4
        with:
          repository: em-foundation/emscript-sdk
          ref: main
          path: emscript-sdk
          token: ${{ secrets.token }}

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Get current version and date
        id: date
        run: |
          echo "date=$(date -u +%Y%m%d%H%M)" >> $GITHUB_OUTPUT
          echo "version=$(cat emscript-releng/VERSION)" >> $GITHUB_OUTPUT

      - name: Create version file, CHANGELOG, etc.
        run: |
          VERSION_WITH_TIMESTAMP=${{ steps.date.outputs.version }}.${{ steps.date.outputs.date }}
          rm -rf emscript-sdk/*
          cp emscript-releng/etc/packages/emscript-sdk/* emscript-sdk/
          echo "${{ steps.date.outputs.version }}" > emscript-sdk/VERSION-${VERSION_WITH_TIMESTAMP}
          echo "${{ steps.date.outputs.date }}" >> emscript-sdk/VERSION-${VERSION_WITH_TIMESTAMP}
          sed -i "s/@VERS/${{ steps.date.outputs.version }}/" emscript-sdk/package.json
          sed -i "s/@FULL/$VERSION_WITH_TIMESTAMP/" emscript-sdk/package.json

      - name: Add workspace
        run: |
          mkdir emscript-sdk/workspace
          cp -r emscript-content/workspace/em.core emscript-sdk/workspace/
          cp -r emscript-content/workspace/ti.cc23xx emscript-sdk/workspace/
          cp emscript-content/workspace/emscript.ini emscript-sdk/workspace/
          cp emscript-content/.clang-format emscript-sdk/
          cp emscript-content/tsconfig.base.json emscript-sdk/

      - name: Build emscript cli
        run: |
          VERSION_WITH_TIMESTAMP=${{ steps.date.outputs.version }}.${{ steps.date.outputs.date }}
          pushd emscript-tools
          npm install
          npm run build-cli
          npm run cli-executable
          sed -i "s/@VERS/$VERSION_WITH_TIMESTAMP/" out/cli/Main.js
          sed -i "s/@VERS/$VERSION_WITH_TIMESTAMP/" out/cli/bin/emscript
          mkdir build
          cp -r $GITHUB_WORKSPACE/emscript-releng/etc/packages/emscript-cli build/
          pushd build/emscript-cli
          sed -i "s/@VERS/${{ steps.date.outputs.version }}/" package.json
          mkdir -p bin
          cp $GITHUB_WORKSPACE/emscript-tools/out/cli/Main.js bin/main.js
          cp $GITHUB_WORKSPACE/emscript-tools/out/cli/bin/emscript bin/
          chmod +x bin/*
          npm pack .
          mv emscript-cli-${{ steps.date.outputs.version }}.tgz emscript-cli-$VERSION_WITH_TIMESTAMP.tgz
          popd
          popd

      - name: Upload Asset to npm-packages resources
        uses: softprops/action-gh-release@v1
        with:
          files: emscript-tools/build/emscript-cli/emscript-cli-*.tgz
          repository: em-foundation/npm-packages
          token: ${{ secrets.token }}
          tag_name: resources
  
      - name: Build VScode extension
        run: |
          VERSION_WITH_TIMESTAMP=${{ steps.date.outputs.version }}.${{ steps.date.outputs.date }}
          pushd emscript-tools
          npm install
          npm version --git-tag-version=false --allow-same-version=true ${{ steps.date.outputs.version }}
          npm run build-ext
          sed -i "s/@VERS/$VERSION_WITH_TIMESTAMP/" out/ext/extension.js
          npx vsce package
          popd
          rm -f emscript-sdk/emscript*.vsix
          cp emscript-tools/emscript-${{ steps.date.outputs.version }}.vsix emscript-sdk/emscript-$VERSION_WITH_TIMESTAMP.vsix
  
      - name: Create package-lock.json
        run: |
          VERSION_WITH_TIMESTAMP=${{ steps.date.outputs.version }}.${{ steps.date.outputs.date }}
          pushd emscript-sdk
          npm install --package-lock-only --ignore-scripts
          popd

      - name: Commit and push changes
        run: |
          pushd emscript-sdk
          git config --global user.name 'build-sdk.yml workflow'
          git config --global user.email 'hello@openem.org'
          git remote set-url origin https://x-access-token:${{ secrets.token }}@github.com/em-foundation/emscript-sdk.git
          git status
          git add --all
          git status
          git commit -m "build-sdk run"
          git push
          popd

      - name: Tag repos
        run: |
          VERSION_WITH_TIMESTAMP=${{ steps.date.outputs.version }}.${{ steps.date.outputs.date }}
          for repo in releng tools content sdk
          do
            pushd emscript-$repo
            git config --global user.name 'build-sdk.yml workflow'
            git config --global user.email 'hello@openem.org'
            git remote set-url origin https://x-access-token:${{ secrets.token }}@github.com/em-foundation/emscript-$repo.git
            git tag ${{ steps.date.outputs.version }}
            git push --tags
            popd
          done
