name: Build tools npm packages from /etc/packages

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout emscript-releng
        uses: actions/checkout@v7
        with:
          path: emscript-releng
          token: ${{ secrets.token }}

      - name: Get parameters
        id: params
        run: |
          echo "PKGS=$GITHUB_WORKSPACE/emscript-releng/etc/packages" >> $GITHUB_OUTPUT
          echo "NPM=$GITHUB_WORKSPACE/emscript-releng/build/npm" >> $GITHUB_OUTPUT
          echo "DATE=$(date -u +%Y%m%d%H%M)" >> $GITHUB_OUTPUT

      - name: Build tools npm packages
        run: |
          for name in segger-arm segger-jlink ti-uniflash
          do
            vers=$(cat ${{ steps.params.outputs.PKGS }}/$name/VERSION)
            root=${{ steps.params.outputs.NPM }}/$name
            mkdir -p $root
            cp -r ${{ steps.params.outputs.PKGS }}/template/* ${root}
            sed -i "s/@NAME/$name/" $root/scripts/install.js
            sed -i "s/@NAME/$name/" $root/package.json
            sed -i "s/@VERS/${vers}/" $root/package.json
            mkdir -p $root/dist
            cp ${{ steps.params.outputs.PKGS }}/$name/*.zip $root/dist
            cp ${{ steps.params.outputs.PKGS }}/$name/LICENSE $root/dist
            touch $root/dist/VERSION-$vers.${{ steps.params.outputs.DATE }}
            pushd $root
            npm pack .
            mv $name*.tgz ../
            popd
          done

      - name: Upload tools packages to npm-packages/resources
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ steps.params.outputs.NPM }}/*.tgz
          repository: em-foundation/npm-packages
          token: ${{ secrets.token }}
          tag_name: resources
          overwrite_files: false
