name: Merge emscript-sdk main from staging

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout emscript-releng
        uses: actions/checkout@v4
        with:
          repository: em-foundation/emscript-releng
          path: emscript-releng
          token: ${{ secrets.token }}

      - name: Checkout emscript-sdk
        uses: actions/checkout@v4
        with:
          repository: em-foundation/emscript-sdk
          ref: main
          fetch-depth: 0
          path: emscript-sdk
          token: ${{ secrets.token }}

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Get current version and date
        id: date
        run: |
          echo "date=$(date -u +%Y%m%d%H%M)" >> $GITHUB_OUTPUT
          echo "version=$(cat emscript-releng/VERSION)" >> $GITHUB_OUTPUT

      - name: Squash-merge staging into main
        run: |
          pushd emscript-sdk
          git config --global user.name 'merge sdk.yml workflow'
          git config --global user.email 'hello@openem.org'
          git remote set-url origin https://x-access-token:${{ secrets.token }}@github.com/em-foundation/emscript-sdk.git
          git merge --squash origin/staging
          git add --all
          git commit -m "merge-sdk run: ${{ steps.date.outputs.version }}"
          git push
          popd

      - name: Tag repo main with shortened tag
        run: |
          pushd emscript-sdk
          git tag ${{ steps.date.outputs.version }}
          git push --tags
          popd

      - name: Merge main back into staging
        run: |
          pushd emscript-sdk
          git checkout staging
          git merge main
          git push
          popd

      - name: Create release from tag / changelog
        uses: softprops/action-gh-release@v2
        with:
          repository: em-foundation/emscript-sdk
          token: ${{ secrets.token }}
          tag_name: ${{ steps.date.outputs.version }}
          body_path: ${{ github.workspace }}/emscript-sdk/CHANGELOG.md
          make_latest: true
