name: Test latest sdk build from staging

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install staging build release
        run: |
          RELEASE_INFO=$(curl -s -H "Authorization: token ${{ secrets.token }}" \
            "${{ github.api_url }}/repos/em-foundation/npm-packages/releases/tags/resources")
          RELEASE_ID=$(echo "$RELEASE_INFO" | jq '.id')
          LATEST_ASSET=$(curl -s -H "Authorization: token ${{ secrets.token }}" \
            "${{ github.api_url }}/repos/em-foundation/npm-packages/releases/${RELEASE_ID}/assets" | jq -r '. [-1].browser_download_url')
          echo "LATEST_ASSET=$LATEST_ASSET"
          mkdir emscript-sdk
          cd emscript-sdk
          pwd
          npm init -y
          npm install $LATEST_ASSET
          for setup in adi.max326xx://default nordic.nrf5x://52-default nordic.nrf5x://54-default ti.cc23xx://default
          do
            for unit in em.etc/em.examples.basic/Ex00_EmptyP.em.ts em.etc/em.examples.basic/Ex02_BlinkerP.em.ts em.etc/em.benchmark.coremark/ActiveRunnerP.em.ts em.etc/em.benchmark.coremark/SleepyRunnerP.em.ts
            do
              pushd workspace
              $(npm prefix)/node_modules/emscript-cli/bin/main.js build --unit $unit -S $setup
              popd
            done
          done 
