name: Test latest sdk build from staging

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Release Assets
        run: |
          RELEASE_INFO=$(curl -s -H "Authorization: token ${{ secrets.token }}" \
            "${{ github.api_url }}/repos/em-foundation/npm-packages/releases/tags/resources")
          RELEASE_ID=$(echo "$RELEASE_INFO" | jq '.id')

          # List release assets using the release ID
          ASSET_NAMES=$(curl -s -H "Authorization: token ${{ secrets.token }}" \
            "${{ github.api_url }}/repos/em-foundation/npm-packages/releases/${RELEASE_ID}/assets" | jq '.[].name' | sort -r)
          echo "ASSET_NAMES=$ASSET_NAMES"
